// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package linear

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// AssignedIssuesResponse is returned by AssignedIssues on success.
type AssignedIssuesResponse struct {
	Viewer AssignedIssuesViewerUser `json:"viewer"`
}

// GetViewer returns AssignedIssuesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *AssignedIssuesResponse) GetViewer() AssignedIssuesViewerUser { return v.Viewer }

// AssignedIssuesViewerUser includes the requested fields of the GraphQL type User.
type AssignedIssuesViewerUser struct {
	AssignedIssues AssignedIssuesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns AssignedIssuesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUser) GetAssignedIssues() AssignedIssuesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// AssignedIssuesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type AssignedIssuesViewerUserAssignedIssuesIssueConnection struct {
	Nodes []AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns AssignedIssuesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnection) GetNodes() []AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	Id          string                                                                            `json:"id"`
	Title       string                                                                            `json:"title"`
	Identifier  string                                                                            `json:"identifier"`
	Priority    float64                                                                           `json:"priority"`
	Parent      AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue        `json:"parent"`
	State       AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState `json:"state"`
	Team        AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam               `json:"team"`
	DueDate     string                                                                            `json:"dueDate"`
	Url         string                                                                            `json:"url"`
	UpdatedAt   string                                                                            `json:"updatedAt"`
	CompletedAt string                                                                            `json:"completedAt"`
}

// GetId returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetTitle returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetIdentifier returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetPriority returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetParent returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Parent, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetParent() AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue {
	return v.Parent
}

// GetState returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetTeam returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Team, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTeam() AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam {
	return v.Team
}

// GetDueDate returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.DueDate, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetDueDate() string {
	return v.DueDate
}

// GetUrl returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.Url, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUrl() string {
	return v.Url
}

// GetUpdatedAt returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetCompletedAt returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue.CompletedAt, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetCompletedAt() string {
	return v.CompletedAt
}

// AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue includes the requested fields of the GraphQL type Issue.
type AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue struct {
	Id string `json:"id"`
}

// GetId returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue.Id, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue) GetId() string {
	return v.Id
}

// AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
type AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// GetName returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam includes the requested fields of the GraphQL type Team.
type AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam struct {
	Name string `json:"name"`
	Key  string `json:"key"`
}

// GetName returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Name, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetName() string {
	return v.Name
}

// GetKey returns AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *AssignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetKey() string {
	return v.Key
}

// StateChangesResponse is returned by StateChanges on success.
type StateChangesResponse struct {
	Viewer StateChangesViewerUser `json:"viewer"`
}

// GetViewer returns StateChangesResponse.Viewer, and is useful for accessing the field via an interface.
func (v *StateChangesResponse) GetViewer() StateChangesViewerUser { return v.Viewer }

// StateChangesViewerUser includes the requested fields of the GraphQL type User.
type StateChangesViewerUser struct {
	AssignedIssues StateChangesViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns StateChangesViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUser) GetAssignedIssues() StateChangesViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// StateChangesViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type StateChangesViewerUserAssignedIssuesIssueConnection struct {
	Nodes []StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns StateChangesViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnection) GetNodes() []StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	Id         string                                                                                     `json:"id"`
	Identifier string                                                                                     `json:"identifier"`
	Title      string                                                                                     `json:"title"`
	Team       StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam                          `json:"team"`
	Url        string                                                                                     `json:"url"`
	UpdatedAt  string                                                                                     `json:"updatedAt"`
	History    StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection `json:"history"`
}

// GetId returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string { return v.Id }

// GetIdentifier returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetTeam returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.Team, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTeam() StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam {
	return v.Team
}

// GetUrl returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.Url, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUrl() string { return v.Url }

// GetUpdatedAt returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetHistory returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue.History, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssue) GetHistory() StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection {
	return v.History
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection includes the requested fields of the GraphQL type IssueHistoryConnection.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection struct {
	Nodes []StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory `json:"nodes"`
}

// GetNodes returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection.Nodes, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnection) GetNodes() []StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory {
	return v.Nodes
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory includes the requested fields of the GraphQL type IssueHistory.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory struct {
	FromState StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState `json:"fromState"`
	ToState   StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState   `json:"toState"`
	CreatedAt string                                                                                                                            `json:"createdAt"`
}

// GetFromState returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory.FromState, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory) GetFromState() StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState {
	return v.FromState
}

// GetToState returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory.ToState, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory) GetToState() StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState {
	return v.ToState
}

// GetCreatedAt returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory.CreatedAt, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistory) GetCreatedAt() string {
	return v.CreatedAt
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState struct {
	Name string `json:"name"`
}

// GetName returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryFromStateWorkflowState) GetName() string {
	return v.Name
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState struct {
	Name string `json:"name"`
}

// GetName returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueHistoryIssueHistoryConnectionNodesIssueHistoryToStateWorkflowState) GetName() string {
	return v.Name
}

// StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam includes the requested fields of the GraphQL type Team.
type StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam struct {
	Name string `json:"name"`
	Key  string `json:"key"`
}

// GetName returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Name, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetName() string {
	return v.Name
}

// GetKey returns StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *StateChangesViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetKey() string {
	return v.Key
}

// UpdatedIssuesWithDetailsResponse is returned by UpdatedIssuesWithDetails on success.
type UpdatedIssuesWithDetailsResponse struct {
	Viewer UpdatedIssuesWithDetailsViewerUser `json:"viewer"`
}

// GetViewer returns UpdatedIssuesWithDetailsResponse.Viewer, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsResponse) GetViewer() UpdatedIssuesWithDetailsViewerUser {
	return v.Viewer
}

// UpdatedIssuesWithDetailsViewerUser includes the requested fields of the GraphQL type User.
type UpdatedIssuesWithDetailsViewerUser struct {
	AssignedIssues UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection `json:"assignedIssues"`
}

// GetAssignedIssues returns UpdatedIssuesWithDetailsViewerUser.AssignedIssues, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUser) GetAssignedIssues() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection {
	return v.AssignedIssues
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection includes the requested fields of the GraphQL type IssueConnection.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection struct {
	Nodes []UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue `json:"nodes"`
}

// GetNodes returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection.Nodes, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnection) GetNodes() []UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue {
	return v.Nodes
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue includes the requested fields of the GraphQL type Issue.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue struct {
	Id          string                                                                                             `json:"id"`
	Identifier  string                                                                                             `json:"identifier"`
	Title       string                                                                                             `json:"title"`
	Description string                                                                                             `json:"description"`
	Priority    float64                                                                                            `json:"priority"`
	Url         string                                                                                             `json:"url"`
	CompletedAt string                                                                                             `json:"completedAt"`
	UpdatedAt   string                                                                                             `json:"updatedAt"`
	State       UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState        `json:"state"`
	Team        UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam                      `json:"team"`
	Parent      UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue               `json:"parent"`
	Comments    UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection `json:"comments"`
}

// GetId returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Id, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Identifier, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetIdentifier() string {
	return v.Identifier
}

// GetTitle returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Title, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTitle() string {
	return v.Title
}

// GetDescription returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Description, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetDescription() string {
	return v.Description
}

// GetPriority returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Priority, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetPriority() float64 {
	return v.Priority
}

// GetUrl returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Url, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUrl() string {
	return v.Url
}

// GetCompletedAt returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.CompletedAt, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetCompletedAt() string {
	return v.CompletedAt
}

// GetUpdatedAt returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.UpdatedAt, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetState returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.State, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetState() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState {
	return v.State
}

// GetTeam returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Team, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetTeam() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam {
	return v.Team
}

// GetParent returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Parent, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetParent() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue {
	return v.Parent
}

// GetComments returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue.Comments, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssue) GetComments() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection {
	return v.Comments
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection includes the requested fields of the GraphQL type CommentConnection.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection struct {
	Nodes []UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment `json:"nodes"`
}

// GetNodes returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnection) GetNodes() []UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment {
	return v.Nodes
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment includes the requested fields of the GraphQL type Comment.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment struct {
	Body      string                                                                                                             `json:"body"`
	CreatedAt string                                                                                                             `json:"createdAt"`
	User      UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser `json:"user"`
}

// GetBody returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment.Body, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment) GetBody() string {
	return v.Body
}

// GetCreatedAt returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment.CreatedAt, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUser returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment.User, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesComment) GetUser() UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser {
	return v.User
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser includes the requested fields of the GraphQL type User.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser struct {
	Name string `json:"name"`
}

// GetName returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser.Name, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueCommentsCommentConnectionNodesCommentUser) GetName() string {
	return v.Name
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue includes the requested fields of the GraphQL type Issue.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue struct {
	Id         string `json:"id"`
	Identifier string `json:"identifier"`
}

// GetId returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue.Id, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue) GetId() string {
	return v.Id
}

// GetIdentifier returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue.Identifier, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueParentIssue) GetIdentifier() string {
	return v.Identifier
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState includes the requested fields of the GraphQL type WorkflowState.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// GetName returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Name, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetName() string {
	return v.Name
}

// GetType returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState.Type, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueStateWorkflowState) GetType() string {
	return v.Type
}

// UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam includes the requested fields of the GraphQL type Team.
type UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam struct {
	Name string `json:"name"`
	Key  string `json:"key"`
}

// GetName returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Name, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetName() string {
	return v.Name
}

// GetKey returns UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam.Key, and is useful for accessing the field via an interface.
func (v *UpdatedIssuesWithDetailsViewerUserAssignedIssuesIssueConnectionNodesIssueTeam) GetKey() string {
	return v.Key
}

// __AssignedIssuesInput is used internally by genqlient
type __AssignedIssuesInput struct {
	Filter map[string]interface{} `json:"filter"`
	First  int                    `json:"first"`
}

// GetFilter returns __AssignedIssuesInput.Filter, and is useful for accessing the field via an interface.
func (v *__AssignedIssuesInput) GetFilter() map[string]interface{} { return v.Filter }

// GetFirst returns __AssignedIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__AssignedIssuesInput) GetFirst() int { return v.First }

// __StateChangesInput is used internally by genqlient
type __StateChangesInput struct {
	Filter       map[string]interface{} `json:"filter"`
	First        int                    `json:"first"`
	HistoryFirst int                    `json:"historyFirst"`
}

// GetFilter returns __StateChangesInput.Filter, and is useful for accessing the field via an interface.
func (v *__StateChangesInput) GetFilter() map[string]interface{} { return v.Filter }

// GetFirst returns __StateChangesInput.First, and is useful for accessing the field via an interface.
func (v *__StateChangesInput) GetFirst() int { return v.First }

// GetHistoryFirst returns __StateChangesInput.HistoryFirst, and is useful for accessing the field via an interface.
func (v *__StateChangesInput) GetHistoryFirst() int { return v.HistoryFirst }

// __UpdatedIssuesWithDetailsInput is used internally by genqlient
type __UpdatedIssuesWithDetailsInput struct {
	Filter        map[string]interface{} `json:"filter"`
	First         int                    `json:"first"`
	CommentsFirst int                    `json:"commentsFirst"`
}

// GetFilter returns __UpdatedIssuesWithDetailsInput.Filter, and is useful for accessing the field via an interface.
func (v *__UpdatedIssuesWithDetailsInput) GetFilter() map[string]interface{} { return v.Filter }

// GetFirst returns __UpdatedIssuesWithDetailsInput.First, and is useful for accessing the field via an interface.
func (v *__UpdatedIssuesWithDetailsInput) GetFirst() int { return v.First }

// GetCommentsFirst returns __UpdatedIssuesWithDetailsInput.CommentsFirst, and is useful for accessing the field via an interface.
func (v *__UpdatedIssuesWithDetailsInput) GetCommentsFirst() int { return v.CommentsFirst }

// The query executed by AssignedIssues.
const AssignedIssues_Operation = `
query AssignedIssues ($filter: IssueFilter!, $first: Int) {
	viewer {
		assignedIssues(filter: $filter, first: $first) {
			nodes {
				id
				title
				identifier
				priority
				parent {
					id
				}
				state {
					name
					type
				}
				team {
					name
					key
				}
				dueDate
				url
				updatedAt
				completedAt
			}
		}
	}
}
`

func AssignedIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	filter map[string]interface{},
	first int,
) (data_ *AssignedIssuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AssignedIssues",
		Query:  AssignedIssues_Operation,
		Variables: &__AssignedIssuesInput{
			Filter: filter,
			First:  first,
		},
	}

	data_ = &AssignedIssuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by StateChanges.
const StateChanges_Operation = `
query StateChanges ($filter: IssueFilter!, $first: Int, $historyFirst: Int) {
	viewer {
		assignedIssues(filter: $filter, first: $first) {
			nodes {
				id
				identifier
				title
				team {
					name
					key
				}
				url
				updatedAt
				history(first: $historyFirst) {
					nodes {
						fromState {
							name
						}
						toState {
							name
						}
						createdAt
					}
				}
			}
		}
	}
}
`

func StateChanges(
	ctx_ context.Context,
	client_ graphql.Client,
	filter map[string]interface{},
	first int,
	historyFirst int,
) (data_ *StateChangesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StateChanges",
		Query:  StateChanges_Operation,
		Variables: &__StateChangesInput{
			Filter:       filter,
			First:        first,
			HistoryFirst: historyFirst,
		},
	}

	data_ = &StateChangesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by UpdatedIssuesWithDetails.
const UpdatedIssuesWithDetails_Operation = `
query UpdatedIssuesWithDetails ($filter: IssueFilter!, $first: Int, $commentsFirst: Int) {
	viewer {
		assignedIssues(filter: $filter, first: $first) {
			nodes {
				id
				identifier
				title
				description
				priority
				url
				completedAt
				updatedAt
				state {
					name
					type
				}
				team {
					name
					key
				}
				parent {
					id
					identifier
				}
				comments(first: $commentsFirst) {
					nodes {
						body
						createdAt
						user {
							name
						}
					}
				}
			}
		}
	}
}
`

func UpdatedIssuesWithDetails(
	ctx_ context.Context,
	client_ graphql.Client,
	filter map[string]interface{},
	first int,
	commentsFirst int,
) (data_ *UpdatedIssuesWithDetailsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdatedIssuesWithDetails",
		Query:  UpdatedIssuesWithDetails_Operation,
		Variables: &__UpdatedIssuesWithDetailsInput{
			Filter:        filter,
			First:         first,
			CommentsFirst: commentsFirst,
		},
	}

	data_ = &UpdatedIssuesWithDetailsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
