---
# golangci-lint configuration for wf directory
# Extends the root configuration with wf-specific rules

version: 2

linters:
  default: all
  disable:
    - depguard
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
    - err113
    - exhaustive
    - exhaustruct
    - funcorder
    - godox
    - gosmopolitan
    - intrange
    - ireturn
    - mnd
    - noctx
    - noinlineerr
    - paralleltest
    - prealloc
    - recvcheck
    - unparam
    - gomoddirectives  # Allow local replace directives for development
    - varnamelen       # Allow short variable names (i, v, tt, etc.)
    - funlen           # Allow longer functions in tests

  settings:
    gocritic:
      enabled-checks:
        - appendAssign
        - assignOp
        - boolExprSimplify
        - builtinShadow
        - captLocal
        - caseOrder
        - codegenComment
        - commentFormatting
        - commentedOutCode
        - defaultCaseOrder
        - deprecatedComment
        - docStub
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - flagDeref
        - flagName
        - hexLiteral
        - hugeParam
        - ifElseChain
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - newDeref
        - nilValReturn
        - octalLiteral
        - offBy1
        - paramTypeCombine
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - regexpMust
        - regexpPattern
        - singleCaseSwitch
        - sloppyLen
        - stringXbytes
        - switchTrue
        - typeAssertChain
        - typeSwitchVar
        - typeUnparen
        - underef
        - unlabelStmt
        - unlambda
        - unnamedResult
        - unnecessaryBlock
        - unslice
        - valSwap
        - weakCond
        - wrapperFunc
        - yodaStyleExpr

    revive:
      rules:
        - name: cognitive-complexity
          arguments: [9]
        - name: cyclomatic
          arguments: [10]
        - name: function-length
          arguments: [50, 0]
        - name: line-length-limit
          arguments: [140]

linters-settings:
  lll:
    line-length: 140
