version: "3"

tasks:
  build:
    desc: Build all binaries
    cmds:
      - task: build:pwgen
      - task: build:gh

  build:pwgen:
    desc: Build pwgen binary
    dir: pwgen
    cmds:
      - go build -o ../bin/pwgen .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - ../bin/pwgen

  build:gh:
    desc: Build gh binary
    dir: gh
    cmds:
      - go build -o ../bin/gh .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - ../bin/gh

  test:
    desc: Run all tests
    cmds:
      - task: test:internal
      - task: test:pwgen
      - task: test:gh

  test:internal:
    desc: Test internal packages
    dir: internal
    cmds:
      - go test -v ./...

  test:pwgen:
    desc: Test pwgen
    dir: pwgen
    cmds:
      - go test -v ./...

  test:gh:
    desc: Test gh
    dir: gh
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - cd internal && golangci-lint run --fix --config ../.golangci.yml ./...
      - cd pwgen && golangci-lint run --fix --config ../.golangci.yml ./...
      - cd gh && golangci-lint run --fix --config ../.golangci.yml ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - cd internal && go mod tidy
      - cd pwgen && go mod tidy
      - cd gh && go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f bin/*

  all:
    desc: Run tidy, test, lint, and build
    cmds:
      - task: tidy
      - task: test
      - task: lint
      - task: build
