version: 2

project_name: docs-alfred

builds:
  - id: ccx
    main: ./cmd/ccx
    binary: ccx
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: data-cli
    main: ./cmd/data-cli
    binary: data-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: docs-cli
    main: ./cmd/docs-cli
    binary: docs-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: gh-alfred
    main: ./cmd/gh-alfred
    binary: gh-alfred
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: linear2nl
    main: ./cmd/linear2nl
    binary: linear2nl
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: pwgen
    main: ./cmd/pwgen
    binary: pwgen
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: rss2nl
    main: ./cmd/rss2nl
    binary: rss2nl
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: xzb
    main: ./cmd/xzb
    binary: xzb
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Documentation updates
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: CI
      regexp: "^.*ci[(\\w)]*:+.*$"
      order: 4
    - title: Others
      order: 5
