version: "3"

includes:
  build: Taskfile.build.yml
  y2m: Taskfile.y2m.yml

tasks:
  feeds-merge:
    desc: feeds-merge
    dir: feeds-merge
    cmds:
      - go run main.go

  pre-commit:
    desc: pre-commit
    cmds:
      - pre-commit run --all-files

  # [REST API endpoints for repositories - GitHub Docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user)
  gh:
    cmds:
      - |
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user/repos


#  lint:
#    des: golang linter
#    cmds:
##      - golangci-lint run --fix && gofumpt -l -w .
##      - go mod tidy -v
##      - fieldalignment -fix ./...
##      - go test `go list ./... | grep -v examples` -coverprofile=coverage.out -covermode=atomic
#      - task: pre-commit

#      - go vet -vettool=$(which shadow) -strict
#      - nilaway ./...
#      - # go build -race cmd
#      - # hadolint --config </path/to/config.yaml> Dockerfile
