version: "3"

includes:
  r2n:
    taskfile: ./cmd/rss2nl/Taskfile.yml
    dir: cmd/rss2nl
  alfred:
    taskfile: .github/taskfile/Taskfile.alfred.yml
    dir: cmd/gh-alfred
    vars:
      BINARY_NAME: gh-alfred
  pwgen:
    taskfile: .github/taskfile/Taskfile.alfred.yml
    dir: cmd/pwgen
    vars:
      BINARY_NAME: pwgen

tasks:
  lint:
    desc: pre-commit
    cmds:
      - pre-commit run --all-files

  test:
    desc: run all tests with coverage
    cmd: set -o pipefail && go test ./... -cover -json | tparse -all

  test-coverprofile:
    desc: generate coverage profile for IDE/CI
    cmds:
      - go test ./... -coverprofile=coverage.out -covermode=atomic
      - go tool cover -func=coverage.out | tail -1
