version: "3"

includes:
  alfred:
    taskfile: ./alfred/Taskfile.yml
    dir: alfred
  y2m:
    taskfile: ./yaml2md/Taskfile.yml
    dir: yaml2md
  merge:
    taskfile: ./gh-merge/Taskfile.yml
    dir: gh-merge
  r2n:
    taskfile: ./rss2newsletter/Taskfile.yml
    dir: rss2newsletter

tasks:
  pre-commit:
    desc: pre-commit
    cmds:
      - pre-commit run --all-files

  lint:
    desc: golang linter
    cmds:
      - golangci-lint run --fix
      - gofumpt -l -w .
      - go mod tidy -v
      - fieldalignment -fix ./...
      - go test `go list ./... | grep -v examples` -coverprofile=coverage.out -covermode=atomic
      - task: pre-commit
      - nilaway ./...
#      - # go build -race cmd
#      - # hadolint --config </path/to/config.yaml> Dockerfile
#      - go vet -vettool=$(which shadow) -strict # 这个回去扫描官方pkg的版本，报错类似 shadow: package requires newer Go version go1.23，所以移除


  test:
    cmd: set -o pipefail && go test ./... -json | tparse -all
