version: "3"

tasks:
  default:
    - task: yaml2md
      vars:
        CMD: gh

  feeds-merge:
    dir: feeds-merge
    cmds:
      - INPUT_FEEDS_PATH="feeds.yml" go run main.go

  yaml2md:
    dir: yaml2md
    cmds:
      - echo "Running command {{.CMD}}"
      - sh -c "go run main.go {{.CMD}} --config {{.CMD}}.yml --target {{.CMD}}.md"
