// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package gh

// JSON Schema for data/gh YAML files. Top-level list of sections; each section
// carries a type plus optional repo/record/topics. Field sets derived from a data
// audit; cross-field and cross-file business rules stay in Go.
type GhSchemaJson []Section

type Record struct {
	// Date corresponds to the JSON schema field "date".
	Date string `json:"date" yaml:"date" mapstructure:"date"`

	// Des corresponds to the JSON schema field "des".
	Des RecordDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type RecordDes *string

type Repo struct {
	// Des corresponds to the JSON schema field "des".
	Des RepoDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Doc corresponds to the JSON schema field "doc".
	Doc *string `json:"doc,omitempty,omitzero" yaml:"doc,omitempty" mapstructure:"doc,omitempty"`

	// IsDotfiles corresponds to the JSON schema field "isDotfiles".
	IsDotfiles *bool `json:"isDotfiles,omitempty,omitzero" yaml:"isDotfiles,omitempty" mapstructure:"isDotfiles,omitempty"`

	// Nix corresponds to the JSON schema field "nix".
	Nix *string `json:"nix,omitempty,omitzero" yaml:"nix,omitempty" mapstructure:"nix,omitempty"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Rel corresponds to the JSON schema field "rel".
	Rel []Repo `json:"rel,omitempty,omitzero" yaml:"rel,omitempty" mapstructure:"rel,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL string `json:"url" yaml:"url" mapstructure:"url"`

	// Zk corresponds to the JSON schema field "zk".
	Zk *string `json:"zk,omitempty,omitzero" yaml:"zk,omitempty" mapstructure:"zk,omitempty"`
}

type RepoDes *string

type Section struct {
	// 本 section 是否 dotfiles 相关
	IsDotfiles *bool `json:"isDotfiles,omitempty,omitzero" yaml:"isDotfiles,omitempty" mapstructure:"isDotfiles,omitempty"`

	// Repo corresponds to the JSON schema field "repo".
	Repo []Repo `json:"repo,omitempty,omitzero" yaml:"repo,omitempty" mapstructure:"repo,omitempty"`

	// 本 section 评分（0-5）
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// 主题列表；必填且至少 1 项，上限 30
	Topics []Topic `json:"topics" yaml:"topics" mapstructure:"topics"`

	// 本节主题（如 golang / mac / kernel）；自由字符串
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// 对比表项；内容异构（name/what/why/where/when/brand/price/lang 等），dynamic key 不做枚举
type TableItem map[string]interface{}

type Topic struct {
	// topic 描述（goods 使用）
	Des TopicDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Hti corresponds to the JSON schema field "hti".
	Hti []string `json:"hti,omitempty,omitzero" yaml:"hti,omitempty" mapstructure:"hti,omitempty"`

	// Hto corresponds to the JSON schema field "hto".
	Hto []string `json:"hto,omitempty,omitzero" yaml:"hto,omitempty" mapstructure:"hto,omitempty"`

	// Htu corresponds to the JSON schema field "htu".
	Htu []string `json:"htu,omitempty,omitzero" yaml:"htu,omitempty" mapstructure:"htu,omitempty"`

	// topic 类型；gh 必填
	Kind TopicKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Repo corresponds to the JSON schema field "repo".
	Repo []Repo `json:"repo,omitempty,omitzero" yaml:"repo,omitempty" mapstructure:"repo,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Table corresponds to the JSON schema field "table".
	Table []TableItem `json:"table,omitempty,omitzero" yaml:"table,omitempty" mapstructure:"table,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`

	// What corresponds to the JSON schema field "what".
	What []string `json:"what,omitempty,omitzero" yaml:"what,omitempty" mapstructure:"what,omitempty"`

	// Why corresponds to the JSON schema field "why".
	Why []string `json:"why,omitempty,omitzero" yaml:"why,omitempty" mapstructure:"why,omitempty"`

	// Ww corresponds to the JSON schema field "ww".
	Ww []string `json:"ww,omitempty,omitzero" yaml:"ww,omitempty" mapstructure:"ww,omitempty"`
}

// topic 描述（goods 使用）
type TopicDes *string

type TopicKind string

const TopicKindMech TopicKind = "mech"
const TopicKindRepo TopicKind = "repo"
const TopicKindTemp TopicKind = "temp"
const TopicKindTools TopicKind = "tools"
const TopicKindType TopicKind = "type"
