version: "3"


tasks:
  gh:
    desc: 【yaml2md gh】生成gh.yml对应的markdown
    dir: yaml2md
    cmds:
      #      - echo "Running command {{.CLI_ARGS}}"
      #      - sh -c "go run main.go {{.CLI_ARGS}} --config {{.CLI_ARGS}}.yml --target {{.CLI_ARGS}}.md"
      - sh -c "go run main.go gh --config {{.CLI_ARGS}}.yml"

  ws:
    desc: 【yaml2md ws】生成ws.yml对应的markdown
    dir: yaml2md
    cmds:
      - sh -c "go run main.go ws --config ws.yml"

  works:
    desc: 【yaml2md works】生成ss.yml对应的markdown
    dir: yaml2md
    cmds:
      - sh -c "go run main.go works --config {{.CLI_ARGS}}.yml"

  goods:
    desc: 【yaml2md goods】生成 goods.yml对应的markdown
    dir: yaml2md
    cmds:
      - sh -c "go run main.go goods --config goods.yml"
