// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package model

// JSON Schema for data/gh YAML files. Top-level list of sections; each section
// carries a type plus optional repo/record/topics. Field sets derived from a data
// audit; cross-field and cross-file business rules stay in Go.
type GhSchemaJson []Section

type Record struct {
	Des   RecordDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`
	Score *int      `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`
	URL   *string   `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
	Date  string    `json:"date" yaml:"date" mapstructure:"date"`
}

type RecordDes *string

type Repo struct {
	Des        RepoDes  `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`
	Doc        *string  `json:"doc,omitempty,omitzero" yaml:"doc,omitempty" mapstructure:"doc,omitempty"`
	IsDotfiles *bool    `json:"isDotfiles,omitempty,omitzero" yaml:"isDotfiles,omitempty" mapstructure:"isDotfiles,omitempty"`
	Nix        *string  `json:"nix,omitempty,omitzero" yaml:"nix,omitempty" mapstructure:"nix,omitempty"`
	Score      *int     `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`
	Zk         *string  `json:"zk,omitempty,omitzero" yaml:"zk,omitempty" mapstructure:"zk,omitempty"`
	URL        string   `json:"url" yaml:"url" mapstructure:"url"`
	Qs         []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`
	Record     []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`
	Rel        []Repo   `json:"rel,omitempty,omitzero" yaml:"rel,omitempty" mapstructure:"rel,omitempty"`
}

type RepoDes *string

type Section struct {
	IsDotfiles *bool   `json:"isDotfiles,omitempty,omitzero" yaml:"isDotfiles,omitempty" mapstructure:"isDotfiles,omitempty"`
	Score      *int    `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`
	Type       string  `json:"type" yaml:"type" mapstructure:"type"`
	Repo       []Repo  `json:"repo,omitempty,omitzero" yaml:"repo,omitempty" mapstructure:"repo,omitempty"`
	Topics     []Topic `json:"topics" yaml:"topics" mapstructure:"topics"`
}

// 对比表项；内容异构（name/what/why/where/when/brand/price/lang 等），dynamic key 不做枚举
type TableItem map[string]interface{}

type Topic struct {
	// topic 描述（goods 使用）
	Des TopicDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Hti corresponds to the JSON schema field "hti".
	Hti []string `json:"hti,omitempty,omitzero" yaml:"hti,omitempty" mapstructure:"hti,omitempty"`

	// Hto corresponds to the JSON schema field "hto".
	Hto []string `json:"hto,omitempty,omitzero" yaml:"hto,omitempty" mapstructure:"hto,omitempty"`

	// Htu corresponds to the JSON schema field "htu".
	Htu []string `json:"htu,omitempty,omitzero" yaml:"htu,omitempty" mapstructure:"htu,omitempty"`

	// topic 类型；gh 必填
	Kind TopicKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Repo corresponds to the JSON schema field "repo".
	Repo []Repo `json:"repo,omitempty,omitzero" yaml:"repo,omitempty" mapstructure:"repo,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Table corresponds to the JSON schema field "table".
	Table []TableItem `json:"table,omitempty,omitzero" yaml:"table,omitempty" mapstructure:"table,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`

	// What corresponds to the JSON schema field "what".
	What []string `json:"what,omitempty,omitzero" yaml:"what,omitempty" mapstructure:"what,omitempty"`

	// Why corresponds to the JSON schema field "why".
	Why []string `json:"why,omitempty,omitzero" yaml:"why,omitempty" mapstructure:"why,omitempty"`

	// Ww corresponds to the JSON schema field "ww".
	Ww []string `json:"ww,omitempty,omitzero" yaml:"ww,omitempty" mapstructure:"ww,omitempty"`
}

// topic 描述（goods 使用）
type TopicDes *string

type TopicKind string

const TopicKindMech TopicKind = "mech"
const TopicKindRepo TopicKind = "repo"
const TopicKindTemp TopicKind = "temp"
const TopicKindTools TopicKind = "tools"
const TopicKindType TopicKind = "type"
