// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package books

// JSON Schema for data/books YAML files (books.*.yml) 与 data/ntl YAML 文件
// (movie/TV/music) 共用的内容收藏 schema。Sections carry type + topics; each topic holds a
// table of rows. 行级 key 严格枚举（additionalProperties false）：共享
// name/author/score/publishAt/des/readAt/url/record/qs，ntl 另有 dict/cast；嵌套内容表
// (row.table / row.topics) 保持 free-form。
type BooksSchemaJson []Section

type Record struct {
	// Date corresponds to the JSON schema field "date".
	Date *string `json:"date,omitempty,omitzero" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// Des corresponds to the JSON schema field "des".
	Des RecordDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type RecordDes *string

type Section struct {
	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Topics corresponds to the JSON schema field "topics".
	Topics []Topic `json:"topics" yaml:"topics" mapstructure:"topics"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type TableItem struct {
	// Author corresponds to the JSON schema field "author".
	Author *string `json:"author,omitempty,omitzero" yaml:"author,omitempty" mapstructure:"author,omitempty"`

	// Cast corresponds to the JSON schema field "cast".
	Cast []string `json:"cast,omitempty,omitzero" yaml:"cast,omitempty" mapstructure:"cast,omitempty"`

	// Des corresponds to the JSON schema field "des".
	Des TableItemDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Dict corresponds to the JSON schema field "dict".
	Dict *string `json:"dict,omitempty,omitzero" yaml:"dict,omitempty" mapstructure:"dict,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// PublishAt corresponds to the JSON schema field "publishAt".
	PublishAt *int `json:"publishAt,omitempty,omitzero" yaml:"publishAt,omitempty" mapstructure:"publishAt,omitempty"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []TableItemQsElem `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// ReadAt corresponds to the JSON schema field "readAt".
	ReadAt *string `json:"readAt,omitempty,omitzero" yaml:"readAt,omitempty" mapstructure:"readAt,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type TableItemDes *string

type TableItemQsElem *string

type Topic struct {
	// Des corresponds to the JSON schema field "des".
	Des TopicDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []TopicQsElem `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Table corresponds to the JSON schema field "table".
	Table []TableItem `json:"table,omitempty,omitzero" yaml:"table,omitempty" mapstructure:"table,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`
}

type TopicDes *string

type TopicQsElem *string
