支出:
  住房:
    备注:
      - 自如
      - 酒店
      - 公寓
    交易对方: []
  交通:
    备注:
      - 哈啰
      - 滴滴
      - 火车票
      - 飞机票
      - 公交
      - 地铁
      - 哈啰单车
      - 滴滴快车
      - 哈啰顺风
    交易对方: []
  餐饮:
    备注:
      - 大众点评
      - 中式点心
      - 食堂
      - 饿了吗
      - 外卖
      - 面馆
      - 美团
      - 餐厅
      - 早点
      - 美食
      - 香锅
      - 肯德基
      - 馄饨
      - 木桶饭
      - 咖喱
      - 西式快餐
      - 烧肉
    交易对方:
      - 肯德基
      - 呷哺呷哺
      - 烧烤
  购物:
    备注:
      - 全家
      - FamilyMart
      - 超市
      - 罗森
      - 京东
      - 淘宝
    交易对方:
      - 超市
  旅行:
    备注: []
    交易对方: []
  人情:
    备注:
      - 爱心捐赠
      - 生日快乐
    交易对方: []
  通信:
    备注:
      - 话费
      - 手机充值
    交易对方: []
  文教:
    备注:
      - iCloud
    交易对方:
      - 腾讯云
  医疗:
    备注:
      - 医院
    交易对方: []
  娱乐:
    备注:
      - 电影票
    交易对方:
      - 苹果充值卡
收入:
  其他:
    备注: []
    交易对方: []
  退款:
    备注: []
    交易对方: []
    交易类型:
      - 退款
  转账:
    备注: []
    交易对方: []
    交易类型:
      - 转账
  红包:
    备注: []
    交易对方:
      - 红包
    交易类型:
      - 红包
  人情:
    备注: []
    交易对方:
      - 生日快乐
    交易类型: []
  工资:
    备注: []
    交易对方: []
  活动:
    备注:
      - 提现
    交易对方:
      - 活动奖励
