version: "3"

vars:
  BINARY_NAME: "{{.BINARY_NAME}}"
  OUTPUT: "{{.BINARY_NAME}}.alfredworkflow"

tasks:
  default:
    desc: Build universal binary and pack .alfredworkflow
    cmds:
      - task: release
        vars:
          ARCH: amd64
      - task: release
        vars:
          ARCH: arm64
      - lipo -create -output .workflow/{{.BINARY_NAME}} {{.BINARY_NAME}}_amd64 {{.BINARY_NAME}}_arm64
      - rm {{.BINARY_NAME}}_amd64 {{.BINARY_NAME}}_arm64
      - cd .workflow && zip -r ../"{{.OUTPUT}}" .

  release:
    desc: Build for a specific architecture
    cmds:
      - GOOS=darwin GOARCH={{.ARCH}} CGO_ENABLED=1 go build -ldflags "-s -w" -o {{.BINARY_NAME}}_{{.ARCH}} .

  build:
    desc: Build for current architecture (dev)
    cmds:
      - go build -o .workflow/{{.BINARY_NAME}} .
