// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package goods

// JSON Schema for data/goods YAML files (goods.*.yml). Field sets verified against
// all goods files including hidden .goods.*.yml. Topics are flat (one level, no
// recursion); there is no kind/repo/rel.
type GoodsSchemaJson []Section

type Record struct {
	// Date corresponds to the JSON schema field "date".
	Date string `json:"date" yaml:"date" mapstructure:"date"`

	// Des corresponds to the JSON schema field "des".
	Des RecordDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Url corresponds to the JSON schema field "url".
	Url *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type RecordDes *string

type Section struct {
	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Topics corresponds to the JSON schema field "topics".
	Topics []Topic `json:"topics" yaml:"topics" mapstructure:"topics"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// 商品项；键异构（name/brand/price/param/des/date/record/isUsing/endDate/endPrice/source/url/alias/developer/playAt/genre/platform/publishAt/status
// 等），不做枚举
type TableItem map[string]interface{}

type Topic struct {
	// Des corresponds to the JSON schema field "des".
	Des TopicDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Hto corresponds to the JSON schema field "hto".
	Hto []string `json:"hto,omitempty,omitzero" yaml:"hto,omitempty" mapstructure:"hto,omitempty"`

	// Htu corresponds to the JSON schema field "htu".
	Htu []string `json:"htu,omitempty,omitzero" yaml:"htu,omitempty" mapstructure:"htu,omitempty"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Table corresponds to the JSON schema field "table".
	Table []TableItem `json:"table,omitempty,omitzero" yaml:"table,omitempty" mapstructure:"table,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`

	// What corresponds to the JSON schema field "what".
	What []string `json:"what,omitempty,omitzero" yaml:"what,omitempty" mapstructure:"what,omitempty"`

	// Why corresponds to the JSON schema field "why".
	Why []string `json:"why,omitempty,omitzero" yaml:"why,omitempty" mapstructure:"why,omitempty"`
}

type TopicDes *string
