// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package goods

// JSON Schema for data/goods YAML files (goods.*.yml). Field sets verified against
// all goods files including hidden .goods.*.yml. Topics are flat (one level, no
// recursion); there is no kind/repo/rel.
type GoodsSchemaJson []Topic

type Record struct {
	// Date corresponds to the JSON schema field "date".
	Date string `json:"date" yaml:"date" mapstructure:"date"`

	// Des corresponds to the JSON schema field "des".
	Des RecordDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type RecordDes *string

// 商品项；key 严格枚举（additionalProperties false），行必有 name；endDate/endPrice/isUsing
// 均为可选生命周期字段
type TableItem struct {
	// Brand corresponds to the JSON schema field "brand".
	Brand *string `json:"brand,omitempty,omitzero" yaml:"brand,omitempty" mapstructure:"brand,omitempty"`

	// Date corresponds to the JSON schema field "date".
	Date *string `json:"date,omitempty,omitzero" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// Des corresponds to the JSON schema field "des".
	Des TableItemDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// EndDate corresponds to the JSON schema field "endDate".
	EndDate *string `json:"endDate,omitempty,omitzero" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// EndPrice corresponds to the JSON schema field "endPrice".
	EndPrice *string `json:"endPrice,omitempty,omitzero" yaml:"endPrice,omitempty" mapstructure:"endPrice,omitempty"`

	// IsUsing corresponds to the JSON schema field "isUsing".
	IsUsing *bool `json:"isUsing,omitempty,omitzero" yaml:"isUsing,omitempty" mapstructure:"isUsing,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Param corresponds to the JSON schema field "param".
	Param *string `json:"param,omitempty,omitzero" yaml:"param,omitempty" mapstructure:"param,omitempty"`

	// Price corresponds to the JSON schema field "price".
	Price *string `json:"price,omitempty,omitzero" yaml:"price,omitempty" mapstructure:"price,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source *string `json:"source,omitempty,omitzero" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

type TableItemDes *string

type Topic struct {
	// Des corresponds to the JSON schema field "des".
	Des TopicDes `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Hto corresponds to the JSON schema field "hto".
	Hto []string `json:"hto,omitempty,omitzero" yaml:"hto,omitempty" mapstructure:"hto,omitempty"`

	// Htu corresponds to the JSON schema field "htu".
	Htu []string `json:"htu,omitempty,omitzero" yaml:"htu,omitempty" mapstructure:"htu,omitempty"`

	// Qs corresponds to the JSON schema field "qs".
	Qs []string `json:"qs,omitempty,omitzero" yaml:"qs,omitempty" mapstructure:"qs,omitempty"`

	// Record corresponds to the JSON schema field "record".
	Record []Record `json:"record,omitempty,omitzero" yaml:"record,omitempty" mapstructure:"record,omitempty"`

	// Score corresponds to the JSON schema field "score".
	Score *int `json:"score,omitempty,omitzero" yaml:"score,omitempty" mapstructure:"score,omitempty"`

	// Table corresponds to the JSON schema field "table".
	Table []TableItem `json:"table,omitempty,omitzero" yaml:"table,omitempty" mapstructure:"table,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`

	// What corresponds to the JSON schema field "what".
	What []string `json:"what,omitempty,omitzero" yaml:"what,omitempty" mapstructure:"what,omitempty"`

	// Why corresponds to the JSON schema field "why".
	Why []string `json:"why,omitempty,omitzero" yaml:"why,omitempty" mapstructure:"why,omitempty"`
}

type TopicDes *string
