// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package goods

type UsingItem struct {
	// Brand corresponds to the JSON schema field "brand".
	Brand *string `json:"brand,omitempty,omitzero" yaml:"brand,omitempty" mapstructure:"brand,omitempty"`

	// Date corresponds to the JSON schema field "date".
	Date *string `json:"date,omitempty,omitzero" yaml:"date,omitempty" mapstructure:"date,omitempty"`

	// Des corresponds to the JSON schema field "des".
	Des *string `json:"des,omitempty,omitzero" yaml:"des,omitempty" mapstructure:"des,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Param corresponds to the JSON schema field "param".
	Param *string `json:"param,omitempty,omitzero" yaml:"param,omitempty" mapstructure:"param,omitempty"`

	// Price corresponds to the JSON schema field "price".
	Price *string `json:"price,omitempty,omitzero" yaml:"price,omitempty" mapstructure:"price,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source *string `json:"source,omitempty,omitzero" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty,omitzero" yaml:"url,omitempty" mapstructure:"url,omitempty"`
}

// Output view of `data-cli goods using`: goods rows with isUsing:true, flattened
// to plain strings and grouped type → topic → items. This is a projection of
// goods.schema.json, not its mirror: it only carries the fields shown in the using
// output.
type UsingSchemaJson []UsingType

type UsingTopic struct {
	// Items corresponds to the JSON schema field "items".
	Items []UsingItem `json:"items" yaml:"items" mapstructure:"items"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`
}

type UsingType struct {
	// Topics corresponds to the JSON schema field "topics".
	Topics []UsingTopic `json:"topics" yaml:"topics" mapstructure:"topics"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}
